import fs from 'fs';

// US State names dictionary
const US_STATES = {
  'AL': { en: 'Alabama', ar: 'ألاباما', fr: 'Alabama', ru: 'Алабама', tr: 'Alabama', de: 'Alabama' },
  'AK': { en: 'Alaska', ar: 'ألاسكا', fr: 'Alaska', ru: 'Аляска', tr: 'Alaska', de: 'Alaska' },
  'AZ': { en: 'Arizona', ar: 'أريزونا', fr: 'Arizona', ru: 'Аризона', tr: 'Arizona', de: 'Arizona' },
  'AR': { en: 'Arkansas', ar: 'أركنساس', fr: 'Arkansas', ru: 'Арканзас', tr: 'Arkansas', de: 'Arkansas' },
  'CA': { en: 'California', ar: 'كاليفورنيا', fr: 'Californie', ru: 'Калифорния', tr: 'Kaliforniya', de: 'Kalifornien' },
  'CO': { en: 'Colorado', ar: 'كولورادو', fr: 'Colorado', ru: 'Колорадо', tr: 'Colorado', de: 'Colorado' },
  'CT': { en: 'Connecticut', ar: 'كونيتيكت', fr: 'Connecticut', ru: 'Коннектикут', tr: 'Connecticut', de: 'Connecticut' },
  'DE': { en: 'Delaware', ar: 'ديلاوير', fr: 'Delaware', ru: 'Делавэр', tr: 'Delaware', de: 'Delaware' },
  'DC': { en: 'District of Columbia', ar: 'واشنطن العاصمة', fr: 'District de Columbia', ru: 'Округ Колумбия', tr: 'Columbia Bölgesi', de: 'District of Columbia' },
  'FL': { en: 'Florida', ar: 'فلوريدا', fr: 'Floride', ru: 'Флорида', tr: 'Florida', de: 'Florida' },
  'GA': { en: 'Georgia', ar: 'جورجيا', fr: 'Géorgie', ru: 'Джорджия', tr: 'Georgia', de: 'Georgia' },
  'HI': { en: 'Hawaii', ar: 'هاواي', fr: 'Hawaï', ru: 'Гавайи', tr: 'Hawaii', de: 'Hawaii' },
  'ID': { en: 'Idaho', ar: 'أيداهو', fr: 'Idaho', ru: 'Айдахо', tr: 'Idaho', de: 'Idaho' },
  'IL': { en: 'Illinois', ar: 'إلينوي', fr: 'Illinois', ru: 'Иллинойс', tr: 'Illinois', de: 'Illinois' },
  'IN': { en: 'Indiana', ar: 'إنديانا', fr: 'Indiana', ru: 'Индиана', tr: 'Indiana', de: 'Indiana' },
  'IA': { en: 'Iowa', ar: 'أيوا', fr: 'Iowa', ru: 'Айова', tr: 'Iowa', de: 'Iowa' },
  'KS': { en: 'Kansas', ar: 'كانساس', fr: 'Kansas', ru: 'Канзас', tr: 'Kansas', de: 'Kansas' },
  'KY': { en: 'Kentucky', ar: 'كنتاكي', fr: 'Kentucky', ru: 'Кентукки', tr: 'Kentucky', de: 'Kentucky' },
  'LA': { en: 'Louisiana', ar: 'لويزيانا', fr: 'Louisiane', ru: 'Луизиана', tr: 'Louisiana', de: 'Louisiana' },
  'ME': { en: 'Maine', ar: 'مين', fr: 'Maine', ru: 'Мэн', tr: 'Maine', de: 'Maine' },
  'MD': { en: 'Maryland', ar: 'ماريلاند', fr: 'Maryland', ru: 'Мэриленд', tr: 'Maryland', de: 'Maryland' },
  'MA': { en: 'Massachusetts', ar: 'ماساتشوستس', fr: 'Massachusetts', ru: 'Массачусетс', tr: 'Massachusetts', de: 'Massachusetts' },
  'MI': { en: 'Michigan', ar: 'ميشيغان', fr: 'Michigan', ru: 'Мичиган', tr: 'Michigan', de: 'Michigan' },
  'MN': { en: 'Minnesota', ar: 'مينيسوتا', fr: 'Minnesota', ru: 'Миннесота', tr: 'Minnesota', de: 'Minnesota' },
  'MS': { en: 'Mississippi', ar: 'مسيسيبي', fr: 'Mississippi', ru: 'Миссисипи', tr: 'Mississippi', de: 'Mississippi' },
  'MO': { en: 'Missouri', ar: 'ميزوري', fr: 'Missouri', ru: 'Миссури', tr: 'Missouri', de: 'Missouri' },
  'MT': { en: 'Montana', ar: 'مونتانا', fr: 'Montana', ru: 'Монтана', tr: 'Montana', de: 'Montana' },
  'NE': { en: 'Nebraska', ar: 'نبراسكا', fr: 'Nebraska', ru: 'Небраска', tr: 'Nebraska', de: 'Nebraska' },
  'NV': { en: 'Nevada', ar: 'نيفادا', fr: 'Nevada', ru: 'Невада', tr: 'Nevada', de: 'Nevada' },
  'NH': { en: 'New Hampshire', ar: 'نيوهامبشير', fr: 'New Hampshire', ru: 'Нью-Гэмпшир', tr: 'New Hampshire', de: 'New Hampshire' },
  'NJ': { en: 'New Jersey', ar: 'نيوجيرسي', fr: 'New Jersey', ru: 'Нью-Джерси', tr: 'New Jersey', de: 'New Jersey' },
  'NM': { en: 'New Mexico', ar: 'نيومكسيكو', fr: 'Nouveau-Mexique', ru: 'Нью-Мексико', tr: 'New Mexico', de: 'New Mexico' },
  'NY': { en: 'New York', ar: 'نيويورك', fr: 'New York', ru: 'Нью-Йорк', tr: 'New York', de: 'New York' },
  'NC': { en: 'North Carolina', ar: 'كارولاينا الشمالية', fr: 'Caroline du Nord', ru: 'Северная Каролина', tr: 'Kuzey Karolina', de: 'North Carolina' },
  'ND': { en: 'North Dakota', ar: 'داكوتا الشمالية', fr: 'Dakota du Nord', ru: 'Северная Дакота', tr: 'Kuzey Dakota', de: 'North Dakota' },
  'OH': { en: 'Ohio', ar: 'أوهايو', fr: 'Ohio', ru: 'Огайо', tr: 'Ohio', de: 'Ohio' },
  'OK': { en: 'Oklahoma', ar: 'أوكلاهوما', fr: 'Oklahoma', ru: 'Оклахома', tr: 'Oklahoma', de: 'Oklahoma' },
  'OR': { en: 'Oregon', ar: 'أوريغون', fr: 'Oregon', ru: 'Орегон', tr: 'Oregon', de: 'Oregon' },
  'PA': { en: 'Pennsylvania', ar: 'بنسيلفانيا', fr: 'Pennsylvanie', ru: 'Пенсильвания', tr: 'Pensilvanya', de: 'Pennsylvania' },
  'RI': { en: 'Rhode Island', ar: 'رود آيلاند', fr: 'Rhode Island', ru: 'Род-Айленд', tr: 'Rhode Island', de: 'Rhode Island' },
  'SC': { en: 'South Carolina', ar: 'كارولاينا الجنوبية', fr: 'Caroline du Sud', ru: 'Южная Каролина', tr: 'Güney Karolina', de: 'South Carolina' },
  'SD': { en: 'South Dakota', ar: 'داكوتا الجنوبية', fr: 'Dakota du Sud', ru: 'Южная Дакота', tr: 'Güney Dakota', de: 'South Dakota' },
  'TN': { en: 'Tennessee', ar: 'تينيسي', fr: 'Tennessee', ru: 'Теннесси', tr: 'Tennessee', de: 'Tennessee' },
  'TX': { en: 'Texas', ar: 'تكساس', fr: 'Texas', ru: 'Техас', tr: 'Teksas', de: 'Texas' },
  'UT': { en: 'Utah', ar: 'يوتا', fr: 'Utah', ru: 'Юта', tr: 'Utah', de: 'Utah' },
  'VT': { en: 'Vermont', ar: 'فيرمونت', fr: 'Vermont', ru: 'Вермонт', tr: 'Vermont', de: 'Vermont' },
  'VA': { en: 'Virginia', ar: 'فيرجينيا', fr: 'Virginie', ru: 'Виргиния', tr: 'Virginia', de: 'Virginia' },
  'WA': { en: 'Washington', ar: 'واشنطن', fr: 'Washington', ru: 'Вашингтон', tr: 'Washington', de: 'Washington' },
  'WV': { en: 'West Virginia', ar: 'فيرجينيا الغربية', fr: 'Virginie-Occidentale', ru: 'Западная Виргиния', tr: 'Batı Virginia', de: 'West Virginia' },
  'WI': { en: 'Wisconsin', ar: 'ويسكونسن', fr: 'Wisconsin', ru: 'Висконсин', tr: 'Wisconsin', de: 'Wisconsin' },
  'WY': { en: 'Wyoming', ar: 'وايومنغ', fr: 'Wyoming', ru: 'Вайоминг', tr: 'Wyoming', de: 'Wyoming' },
  'AS': { en: 'American Samoa', ar: 'ساموا الأمريكية', fr: 'Samoa américaines', ru: 'Американское Самоа', tr: 'Amerikan Samoası', de: 'Amerikanisch-Samoa' },
  'GU': { en: 'Guam', ar: 'غوام', fr: 'Guam', ru: 'Гуам', tr: 'Guam', de: 'Guam' },
  'MP': { en: 'Northern Mariana Islands', ar: 'جزر ماريانا الشمالية', fr: 'Îles Mariannes du Nord', ru: 'Северные Марианские острова', tr: 'Kuzey Mariana Adaları', de: 'Nördliche Marianen' },
  'PR': { en: 'Puerto Rico', ar: 'بورتوريكو', fr: 'Porto Rico', ru: 'Пуэрто-Рико', tr: 'Porto Riko', de: 'Puerto Rico' },
  'VI': { en: 'Virgin Islands', ar: 'الجزر العذراء الأمريكية', fr: 'Îles Vierges des États-Unis', ru: 'Виргинские острова', tr: 'Virgin Adaları', de: 'Amerikanische Jungferninseln' }
};

// 65 Non-US regions dictionary
const NON_US_REGIONS = {
  'Abu Dhabi': { en: 'Abu Dhabi', ar: 'أبو ظبي', fr: 'Abou Dabi', ru: 'Абу-Даби', tr: 'Abu Dabi', de: 'Abu Dhabi' },
  'Ajman': { en: 'Ajman', ar: 'عجمان', fr: 'Ajman', ru: 'Аджман', tr: 'Acman', de: 'Adschman' },
  'Al Ahmadi': { en: 'Al Ahmadi', ar: 'الأحمدي', fr: 'Al Ahmadi', ru: 'Эль-Ахмади', tr: 'Ahmedi', de: 'al-Ahmadi' },
  'Al Batinah Region north': { en: 'North Al Batinah', ar: 'شمال الباطنة', fr: 'Al Batinah Nord', ru: 'Северная Эль-Батина', tr: 'Kuzey El Batina', de: 'Schamal al-Batina' },
  'Al Batinah Region south': { en: 'South Al Batinah', ar: 'جنوب الباطنة', fr: 'Al Batinah Sud', ru: 'Южная Эль-Батина', tr: 'Güney El Batina', de: 'Dschanub al-Batina' },
  'Al Buraymi': { en: 'Al Buraimi', ar: 'البريمي', fr: 'Al Buraymi', ru: 'Эль-Бурайми', tr: 'El Bureymi', de: 'al-Buraimi' },
  'Al Dhahirah': { en: 'Ad Dhahirah', ar: 'الظاهرة', fr: 'Ad Dhahirah', ru: 'Эз-Захира', tr: 'Ez Zahire', de: 'az-Zahira' },
  'Al Doha': { en: 'Doha', ar: 'الدوحة', fr: 'Doha', ru: 'Доха', tr: 'Doha', de: 'Doha' },
  'Al Rayyan': { en: 'Al Rayyan', ar: 'الريان', fr: 'Al Rayyan', ru: 'Эр-Райян', tr: 'El Reyyan', de: 'ar-Rayyan' },
  'Al Sharqiyah North': { en: 'North Al Sharqiyah', ar: 'شمال الشرقية', fr: 'Ach-Charqiya du Nord', ru: 'Северная Эш-Шаркия', tr: 'Kuzey Şarkiye', de: 'Schamal asch-Scharqiyya' },
  'Al Sharqiyah South': { en: 'South Al Sharqiyah', ar: 'جنوب الشرقية', fr: 'Ach-Charqiya du Sud', ru: 'Южная Эш-Шаркия', tr: 'Güney Şarkiye', de: 'Dschanub asch-Scharqiyya' },
  'Al Wadi Al Gadid': { en: 'New Valley', ar: 'الوادي الجديد', fr: 'Nouvelle-Vallée', ru: 'Новая Долина', tr: 'Yeni Vadi', de: 'Neues Tal' },
  'Al Wakrah': { en: 'Al Wakrah', ar: 'الوكرة', fr: 'Al Wakrah', ru: 'Эль-Вакра', tr: 'El Vakra', de: 'al-Wakra' },
  'Alexandria': { en: 'Alexandria', ar: 'الإسكندرية', fr: 'Alexandrie', ru: 'Александрия', tr: 'İskenderiye', de: 'Alexandria' },
  'Amman': { en: 'Amman', ar: 'عمّان', fr: 'Amman', ru: 'Амман', tr: 'Amman', de: 'Amman' },
  'Assiut': { en: 'Asyut', ar: 'أسيوط', fr: 'Assiout', ru: 'Асьют', tr: 'Asyut', de: 'Asyut' },
  'Aswan': { en: 'Aswan', ar: 'أسوان', fr: 'Assouan', ru: 'Асуан', tr: 'Aswan', de: 'Assuan' },
  'Bahrain': { en: 'Bahrain', ar: 'البحرين', fr: 'Bahreïn', ru: 'Бахрейн', tr: 'Bahreyn', de: 'Bahrain' },
  'Beheira': { en: 'Beheira', ar: 'البحيرة', fr: 'Beheira', ru: 'Бухейра', tr: 'Buheyre', de: 'Beheira' },
  'Beni Suef': { en: 'Beni Suef', ar: 'بني سويف', fr: 'Beni Souef', ru: 'Бени-Суэйф', tr: 'Beni Suef', de: 'Bani Suwaif' },
  'Cairo': { en: 'Cairo', ar: 'القاهرة', fr: 'Le Caire', ru: 'Каир', tr: 'Kahire', de: 'Kairo' },
  'Dakahlia': { en: 'Dakahlia', ar: 'الدقهلية', fr: 'Dakhleya', ru: 'Дакахлия', tr: 'Dakahliye', de: 'Dakahlia' },
  'Dakhiliyah': { en: 'Ad Dakhiliyah', ar: 'الداخلية', fr: 'Ad Dakhiliyah', ru: 'Эд-Дахилия', tr: 'Ed Dahiliye', de: 'ad-Dachiliyya' },
  'Damietta': { en: 'Damietta', ar: 'دمياط', fr: 'Damiette', ru: 'Дамиетта', tr: 'Dimyat', de: 'Damiette' },
  'Daqahleya': { en: 'Dakahlia', ar: 'الدقهلية', fr: 'Dakhleya', ru: 'Дакахлия', tr: 'Dakahliye', de: 'Dakahlia' },
  'Dhofar': { en: 'Dhofar', ar: 'ظفار', fr: 'Dhofar', ru: 'Дофар', tr: 'Zufar', de: 'Dhofar' },
  'Dubai': { en: 'Dubai', ar: 'دبي', fr: 'Dubaï', ru: 'Дубай', tr: 'Dubai', de: 'Dubai' },
  'Farwaniya': { en: 'Farwaniya', ar: 'الفروانية', fr: 'Farwaniya', ru: 'Эль-Фарвания', tr: 'Fervaniye', de: 'al-Farwaniyya' },
  'Fayoum': { en: 'Faiyum', ar: 'الفيوم', fr: 'Fayoum', ru: 'Файюм', tr: 'Feyyum', de: 'Faiyum' },
  'Fujairah': { en: 'Fujairah', ar: 'الفجيرة', fr: 'Fujaïrah', ru: 'Эль-Фуджайра', tr: 'Füceyre', de: 'Fudschaira' },
  'Gharbia': { en: 'Gharbia', ar: 'الغربية', fr: 'Gharbeya', ru: 'Гарбия', tr: 'Garbiye', de: 'Gharbia' },
  'Giza': { en: 'Giza', ar: 'الجيزة', fr: 'Gizeh', ru: 'Гиза', tr: 'Gize', de: 'Gizeh' },
  'Hawally': { en: 'Hawalli', ar: 'حولي', fr: 'Hawalli', ru: 'Хавалли', tr: 'Havalli', de: 'Hawalli' },
  'Hurghada': { en: 'Hurghada', ar: 'الغردقة', fr: 'Hurghada', ru: 'Хургада', tr: 'Hurgada', de: 'Hurghada' },
  'Ismailia': { en: 'Ismailia', ar: 'الإسماعيلية', fr: 'Ismaïlia', ru: 'Исмаилия', tr: 'İsmailiye', de: 'Ismailia' },
  'Jahra': { en: 'Al Jahra', ar: 'الجهراء', fr: 'Al Jahra', ru: 'Эль-Джахра', tr: 'Cehre', de: 'al-Dschahra' },
  'Kafr Al Sheikh': { en: 'Kafr El Sheikh', ar: 'كفر الشيخ', fr: 'Kafr el-Cheik', ru: 'Кафр-эш-Шейх', tr: 'Kefr el-Şeyh', de: 'Kafr asch-Schaich' },
  'Kuwait City': { en: 'Kuwait City', ar: 'مدينة الكويت', fr: 'Koweït (Ville)', ru: 'Эль-Кувейт', tr: 'Kuveyt Şehri', de: 'Kuwait-Stadt' },
  'Luxor': { en: 'Luxor', ar: 'الأقصر', fr: 'Louxor', ru: 'Луксор', tr: 'Luksor', de: 'Luxor' },
  'Mahboula': { en: 'Mahboula', ar: 'المهبولة', fr: 'Mahboula', ru: 'Махбула', tr: 'Mahbula', de: 'Mahboula' },
  'Manama': { en: 'Manama', ar: 'المنامة', fr: 'Manama', ru: 'Манама', tr: 'Manama', de: 'Manama' },
  'Matrouh': { en: 'Matrouh', ar: 'مطروح', fr: 'Matruh', ru: 'Матрух', tr: 'Matruh', de: 'Matruh' },
  'Menoufia': { en: 'Monufia', ar: 'المنوفية', fr: 'Menufiya', ru: 'Минуфия', tr: 'Menufiye', de: 'Menofia' },
  'Minya': { en: 'Minya', ar: 'المنيا', fr: 'Al-Minya', ru: 'Эль-Минья', tr: 'Minye', de: 'al-Minya' },
  'Mubarak Al Kabeer': { en: 'Mubarak Al-Kabeer', ar: 'مبارك الكبير', fr: 'Mubarak Al-Kabeer', ru: 'Мубарак аль-Кабир', tr: 'Mübarek El Kebir', de: 'Mubarak al-Kabir' },
  'Muharraq': { en: 'Muharraq', ar: 'المحرق', fr: 'Muharraq', ru: 'Мухаррак', tr: 'Muharrak', de: 'al-Muharraq' },
  'Muscat': { en: 'Muscat', ar: 'مسقط', fr: 'Mascate', ru: 'Маскат', tr: 'Maskat', de: 'Maskat' },
  'North Sinai': { en: 'North Sinai', ar: 'شمال سيناء', fr: 'Sinaï Nord', ru: 'Северный Синай', tr: 'Kuzey Sina', de: 'Nord-Sinai' },
  'Northen': { en: 'Northern Governorate', ar: 'المحافظة الشمالية', fr: 'Gouvernorat septentrional', ru: 'Северная мухафаза', tr: 'Kuzey Valiliği', de: 'Nördliches Gouvernement' },
  'Oman': { en: 'Oman', ar: 'سلطنة عمان', fr: 'Oman', ru: 'Оман', tr: 'Umman', de: 'Oman' },
  'Port Said': { en: 'Port Said', ar: 'بورسعيد', fr: 'Port-Saïd', ru: 'Порт-Саид', tr: 'Port Said', de: 'Port Said' },
  'Qalubiya': { en: 'Qalyubia', ar: 'القليوبية', fr: 'Qalyubiya', ru: 'Кальюбия', tr: 'Kalyubiye', de: 'Qalyubia' },
  'Qatar': { en: 'Qatar', ar: 'قطر', fr: 'Qatar', ru: 'Катар', tr: 'Katar', de: 'Katar' },
  'Qena': { en: 'Qena', ar: 'قنا', fr: 'Qena', ru: 'Кена', tr: 'Kina', de: 'Qina' },
  'Ras al Khaimah': { en: 'Ras Al Khaimah', ar: 'رأس الخيمة', fr: 'Ras el Khaïmah', ru: 'Рас-эль-Хайма', tr: 'Resü\'l-Hayme', de: 'Ras al-Chaima' },
  'Red Sea': { en: 'Red Sea', ar: 'البحر الأحمر', fr: 'Mer Rouge', ru: 'Красное Море', tr: 'Kızıldeniz', de: 'Rotes Meer' },
  'Sharjah': { en: 'Sharjah', ar: 'الشارقة', fr: 'Charjah', ru: 'Шарджа', tr: 'Şarika', de: 'Schardscha' },
  'Sharkia': { en: 'Sharkia', ar: 'الشرقية', fr: 'Ach-Charqiya', ru: 'Эш-Шаркия', tr: 'Şarkiye', de: 'Asch-Scharkiyya' },
  'Sohag': { en: 'Sohag', ar: 'سوهاج', fr: 'Sohag', ru: 'Сохаг', tr: 'Suhac', de: 'Sohag' },
  'Sourthen': { en: 'Southern Governorate', ar: 'المحافظة الجنوبية', fr: 'Gouvernorat méridional', ru: 'Южная мухафаза', tr: 'Güney Valiliği', de: 'Südliches Gouvernement' },
  'South Sinai': { en: 'South Sinai', ar: 'جنوب سيناء', fr: 'Sinaï Sud', ru: 'Южный Синай', tr: 'Güney Sina', de: 'Süd-Sinai' },
  'South sinai': { en: 'South Sinai', ar: 'جنوب سيناء', fr: 'Sinaï Sud', ru: 'Южный Синай', tr: 'Güney Sina', de: 'Süd-Sinai' },
  'Suez': { en: 'Suez', ar: 'السويس', fr: 'Suez', ru: 'Суэц', tr: 'Süveyş', de: 'Sues' },
  'Tanta': { en: 'Tanta', ar: 'طنطا', fr: 'Tanta', ru: 'Танта', tr: 'Tanta', de: 'Tanta' },
  'Umm Al Quwain': { en: 'Umm Al Quwain', ar: 'أم القيوين', fr: 'Oumm al Qaïwaïn', ru: 'Умм-эль-Кайвайн', tr: 'Ummül-Kayveyn', de: 'Umm al-Qaiwain' }
};

const allRegions = { ...US_STATES, ...NON_US_REGIONS };

fs.writeFileSync('all_regions_mapped.json', JSON.stringify(allRegions, null, 2), 'utf8');
console.log('Total regions generated:', Object.keys(allRegions).length);

const geo = JSON.parse(fs.readFileSync('geo_audit_dump.json', 'utf8'));
const missing = geo.regions.filter(r => !allRegions[r]);
console.log('Missing regions from DB:', missing.length, missing);
