// frontend/src/components/TicketSystem.jsx
// ============================================================
// SHARED SUPPORT TICKET SYSTEM
// Used by WorkerComplaints (red theme) and EmployerComplaints (teal theme).
// Reuses the existing complaint API. No backend changes.
// ============================================================
import React, { useState, useEffect, useCallback } from 'react';
import {
  X,
  AlertTriangle,
  Send,
  Clock,
  CheckCircle,
  AlertCircle,
  FileText,
  Search,
  Paperclip,
  MessageSquare,
  History,
  Flag,
  ArrowUpRight,
  Lock,
  User as UserIcon,
  Shield,
  RefreshCw,
  RotateCcw,
  Calendar,
  Tag,
  LifeBuoy,
  Inbox,
  Loader2,
  ChevronDown,
  ChevronUp
} from 'lucide-react';
import complaintsService from '../services/complaintService';
import { UserDisplayName } from './users';

// ============================================================
// THEME CONFIG
// ============================================================
const THEMES = {
  red: {
    gradient: 'from-red-600 via-red-700 to-red-800',
    text: 'text-red-600',
    textDark: 'text-red-600 dark:text-red-400',
    bg: 'bg-red-50 dark:bg-red-900/30',
    ring: 'focus:ring-red-500',
    button: 'bg-gradient-to-r from-red-600 to-red-700',
    buttonHover: 'hover:shadow-lg',
    dot: 'bg-red-500',
    bubble: 'bg-red-50 dark:bg-red-900/30 border-red-200 dark:border-red-800',
    icon: 'text-red-600',
    headerBtn: 'bg-white text-red-600 hover:bg-gray-100 dark:bg-gray-800/20 dark:hover:bg-gray-800/30'
  },
  teal: {
    gradient: 'from-teal-600 to-teal-700',
    text: 'text-teal-600',
    textDark: 'text-teal-600 dark:text-teal-400',
    bg: 'bg-teal-50 dark:bg-teal-900/30',
    ring: 'focus:ring-teal-500',
    button: 'bg-teal-600',
    buttonHover: 'hover:bg-teal-700',
    dot: 'bg-teal-500',
    bubble: 'bg-teal-50 dark:bg-teal-900/30 border-teal-200 dark:border-teal-800',
    icon: 'text-teal-600',
    headerBtn: 'bg-white text-teal-600 hover:bg-gray-100 dark:bg-gray-800/20 dark:hover:bg-gray-800/30'
  }
};

// ============================================================
// HELPERS
// ============================================================

// Ticket number is generated by the backend and returned directly.
// Fallback for legacy records that predate ticketNumber.
const getTicketNumber = (ticket) => {
  if (ticket?.ticketNumber) return ticket.ticketNumber;
  return `HS-${String(ticket?.id || '').slice(-6) || '000000'}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

const formatShortDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
};

// ============================================================
// MAIN COMPONENT
// ============================================================
const TicketSystem = ({ theme = 'red', userRole = 'WORKER' }) => {
  const th = THEMES[theme] || THEMES.red;

  // State
  const [tickets, setTickets] = useState([]);
  const [filtered, setFiltered] = useState([]);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [priorityFilter, setPriorityFilter] = useState('all');
  const [loading, setLoading] = useState(true);
  const [showCreate, setShowCreate] = useState(false);
  const [selected, setSelected] = useState(null);
  const [showDetails, setShowDetails] = useState(false);
  const [timeline, setTimeline] = useState([]);
  const [replyText, setReplyText] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [sendingReply, setSendingReply] = useState(false);
  const [reopening, setReopening] = useState(false);
  const [notification, setNotification] = useState(null);
  const [confirmDialog, setConfirmDialog] = useState(null);
  const [newTicket, setNewTicket] = useState({
    subject: '',
    description: '',
    category: 'Other',
    priority: 'Medium',
    attachments: []
  });

  // Translations
  const translations = {
    en: {
      title: 'Support Tickets',
      subtitle: 'Submit and track your support tickets',
      newTicket: 'New Ticket',
      cancel: 'Cancel',
      stats: { total: 'Total Tickets', open: 'Open', inProgress: 'In Progress', resolved: 'Resolved' },
      filters: {
        all: 'All Tickets', new: 'New', open: 'Open', inProgress: 'In Progress',
        waiting: 'Waiting for User', escalated: 'Escalated', resolved: 'Resolved', closed: 'Closed',
        allPriorities: 'All Priorities'
      },
      searchPlaceholder: 'Search tickets...',
      ticketId: 'Ticket ID',
      subject: 'Subject',
      category: 'Category',
      status: 'Status',
      priority: 'Priority',
      assigned: 'Assigned Support',
      unassigned: 'Unassigned',
      supportTeam: 'Support Team',
      created: 'Created',
      lastUpdate: 'Last Update',
      description: 'Description',
      attachments: 'Attachments',
      noAttachments: 'No attachments',
      timeline: 'Timeline',
      conversation: 'Conversation',
      reply: 'Reply',
      replyPlaceholder: 'Type your reply...',
      sendReply: 'Send Reply',
      viewDetails: 'View Details',
      close: 'Close',
      reopen: 'Reopen Ticket',
      confirmReopen: 'Are you sure you want to reopen this ticket?',
      confirm: 'Confirm',
      noTickets: 'No tickets found',
      noTicketsDesc: 'Submit a ticket and our support team will help you',
      loading: 'Loading tickets...',
      showing: 'Showing',
      tickets: 'tickets',
      replySent: 'Reply sent successfully',
      replyFailed: 'Failed to send reply',
      ticketCreated: 'Ticket submitted successfully',
      ticketFailed: 'Failed to submit ticket',
      reopened: 'Ticket reopened. Support will respond shortly.',
      reopenFailed: 'Failed to reopen ticket',
      submitting: 'Submitting...',
      sending: 'Sending...',
      reopening: 'Reopening...',
      titleLabel: 'Subject',
      categoryLabel: 'Category',
      priorityLabel: 'Priority',
      descriptionLabel: 'Description',
      attachmentsLabel: 'Attachments (optional)',
      submit: 'Submit Ticket',
      you: 'You',
      system: 'System',
      admin: 'Admin',
      support: 'Support',
      eventLabels: {
        CREATED: 'Ticket Created',
        USER_REPLIED: 'You Replied',
        SUPPORT_REPLIED: 'Support Replied',
        ADMIN_REPLIED: 'Admin Replied',
        ASSIGNED: 'Support Assigned',
        STATUS_CHANGED: 'Status Changed',
        ESCALATED: 'Escalated',
        RESOLVED: 'Resolved',
        CLOSED: 'Closed',
        NOTE_ADDED: 'Internal Note Added',
        REASSIGNED: 'Reassigned',
        RETURNED_TO_SUPPORT: 'Returned to Support'
      }
    },
    ar: {
      title: 'تذاكر الدعم',
      subtitle: 'تقديم وتتبع تذاكر الدعم الخاصة بك',
      newTicket: 'تذكرة جديدة',
      cancel: 'إلغاء',
      stats: { total: 'إجمالي التذاكر', open: 'مفتوحة', inProgress: 'قيد المعالجة', resolved: 'تم الحل' },
      filters: {
        all: 'جميع التذاكر', new: 'جديدة', open: 'مفتوحة', inProgress: 'قيد المعالجة',
        waiting: 'بانتظار المستخدم', escalated: 'مرفوعة', resolved: 'تم الحل', closed: 'مغلقة',
        allPriorities: 'جميع الأولويات'
      },
      searchPlaceholder: 'ابحث في التذاكر...',
      ticketId: 'رقم التذكرة',
      subject: 'الموضوع',
      category: 'الفئة',
      status: 'الحالة',
      priority: 'الأولوية',
      assigned: 'الدعم المعين',
      unassigned: 'غير معين',
      supportTeam: 'فريق الدعم',
      created: 'تاريخ الإنشاء',
      lastUpdate: 'آخر تحديث',
      description: 'الوصف',
      attachments: 'المرفقات',
      noAttachments: 'لا توجد مرفقات',
      timeline: 'الخط الزمني',
      conversation: 'المحادثة',
      reply: 'رد',
      replyPlaceholder: 'اكتب ردك...',
      sendReply: 'إرسال الرد',
      viewDetails: 'عرض التفاصيل',
      close: 'إغلاق',
      reopen: 'إعادة فتح التذكرة',
      confirmReopen: 'هل أنت متأكد من إعادة فتح هذه التذكرة؟',
      confirm: 'تأكيد',
      noTickets: 'لا توجد تذاكر',
      noTicketsDesc: 'قدم تذكرة وسيساعدك فريق الدعم',
      loading: 'جاري تحميل التذاكر...',
      showing: 'عرض',
      tickets: 'تذاكر',
      replySent: 'تم إرسال الرد بنجاح',
      replyFailed: 'فشل إرسال الرد',
      ticketCreated: 'تم تقديم التذكرة بنجاح',
      ticketFailed: 'فشل تقديم التذكرة',
      reopened: 'تم إعادة فتح التذكرة. سيرد الدعم قريباً.',
      reopenFailed: 'فشل إعادة فتح التذكرة',
      submitting: 'جاري التقديم...',
      sending: 'جاري الإرسال...',
      reopening: 'جاري إعادة الفتح...',
      titleLabel: 'الموضوع',
      categoryLabel: 'الفئة',
      priorityLabel: 'الأولوية',
      descriptionLabel: 'الوصف',
      attachmentsLabel: 'المرفقات (اختياري)',
      submit: 'تقديم التذكرة',
      you: 'أنت',
      system: 'النظام',
      admin: 'المشرف',
      support: 'الدعم',
      eventLabels: {
        CREATED: 'تم إنشاء التذكرة',
        USER_REPLIED: 'قمت بالرد',
        SUPPORT_REPLIED: 'رد الدعم',
        ADMIN_REPLIED: 'رد المشرف',
        ASSIGNED: 'تم تعيين الدعم',
        STATUS_CHANGED: 'تغيرت الحالة',
        ESCALATED: 'تم الرفع',
        RESOLVED: 'تم الحل',
        CLOSED: 'مغلقة',
        NOTE_ADDED: 'تمت إضافة ملاحظة',
        REASSIGNED: 'تمت إعادة التعيين',
        RETURNED_TO_SUPPORT: 'أعيدت للدعم'
      }
    }
  };

  const lang = localStorage.getItem('homelyserv_language') === 'ar' ? 'ar' : 'en';
  const t = translations[lang];

  // ============================================================
  // LOAD TICKETS
  // ============================================================
  const loadTickets = useCallback(async () => {
    try {
      setLoading(true);
      const data = await complaintsService.getMyComplaints();
      if (data?.success) {
        setTickets(data.complaints || []);
        setFiltered(data.complaints || []);
      }
    } catch (error) {
      console.error('❌ Error loading tickets:', error);
      setTickets([]);
      setFiltered([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadTickets();
  }, [loadTickets]);

  // ============================================================
  // FILTERS
  // ============================================================
  useEffect(() => {
    let result = tickets;
    if (statusFilter !== 'all') {
      result = result.filter(t => t.status === statusFilter);
    }
    if (priorityFilter !== 'all') {
      result = result.filter(t => t.priority === priorityFilter);
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      result = result.filter(t =>
        t.subject?.toLowerCase().includes(q) ||
        t.description?.toLowerCase().includes(q) ||
        (t.category || '').toLowerCase().includes(q) ||
        getTicketNumber(t).toLowerCase().includes(q)
      );
    }
    setFiltered(result);
  }, [tickets, statusFilter, priorityFilter, search]);

  // ============================================================
  // CREATE TICKET
  // ============================================================
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setNewTicket(prev => ({ ...prev, [name]: value }));
  };

  const handleAttachmentChange = async (e) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0) return;

    // Show local previews immediately
    const previews = files.map(file => URL.createObjectURL(file));
    setNewTicket(prev => ({ ...prev, attachments: [...prev.attachments, ...previews] }));

    // Upload each file to the backend and replace the blob URL with the permanent URL
    for (let i = 0; i < files.length; i++) {
      try {
        const data = await complaintsService.uploadComplaintAttachment(files[i]);
        if (data?.success && data.url) {
          setNewTicket(prev => {
            const updated = [...prev.attachments];
            const previewIndex = updated.indexOf(previews[i]);
            if (previewIndex !== -1) {
              updated[previewIndex] = data.url;
            }
            return { ...prev, attachments: updated };
          });
        }
      } catch (error) {
        console.error('❌ Error uploading attachment:', error);
        setNotification({ type: 'error', text: 'Failed to upload attachment' });
      }
    }
  };

  const removeAttachment = (index) => {
    setNewTicket(prev => ({ ...prev, attachments: prev.attachments.filter((_, i) => i !== index) }));
  };

  const handleCreate = async (e) => {
    e.preventDefault();
    setSubmitting(true);
    try {
      const data = await complaintsService.createComplaint({
        subject: newTicket.subject,
        description: newTicket.description,
        category: newTicket.category,
        priority: newTicket.priority,
        attachments: newTicket.attachments
      });
      if (data?.success) {
        setNotification({ type: 'success', text: t.ticketCreated });
        setNewTicket({ subject: '', description: '', category: 'Other', priority: 'Medium', attachments: [] });
        setShowCreate(false);
        loadTickets();
      }
    } catch (error) {
      console.error('❌ Error creating ticket:', error);
      setNotification({ type: 'error', text: t.ticketFailed });
    } finally {
      setSubmitting(false);
    }
  };

  // ============================================================
  // VIEW DETAILS
  // ============================================================
  const handleViewDetails = async (ticket) => {
    setSelected(ticket);
    setShowDetails(true);
    setReplyText('');
    try {
      const data = await complaintsService.getComplaintById(ticket.id);
      if (data?.success) {
        setSelected(data.complaint);
        setTimeline(data.timeline || []);
      }
    } catch (error) {
      console.error('❌ Error fetching ticket details:', error);
      setTimeline([]);
    }
  };

  // ============================================================
  // SEND REPLY
  // ============================================================
  const handleSendReply = async () => {
    if (!replyText.trim() || !selected) return;
    setSendingReply(true);
    try {
      const data = await complaintsService.userReplyToComplaint(selected.id, replyText);
      if (data?.success) {
        setNotification({ type: 'success', text: t.replySent });
        setReplyText('');
        setSelected(data.complaint);
        const detail = await complaintsService.getComplaintById(selected.id);
        if (detail?.success) {
          setSelected(detail.complaint);
          setTimeline(detail.timeline || []);
        }
        loadTickets();
      }
    } catch (error) {
      console.error('❌ Error sending reply:', error);
      setNotification({ type: 'error', text: t.replyFailed });
    } finally {
      setSendingReply(false);
    }
  };

  // ============================================================
  // REOPEN TICKET (RESOLVED / CLOSED)
  // Reuses the existing reply API. The reply is recorded and the
  // ticket is optimistically marked as reopened in the UI.
  // ============================================================
  const handleReopen = async () => {
    if (!selected) return;
    setReopening(true);
    try {
      const data = await complaintsService.userReplyToComplaint(selected.id, 'Ticket reopened by user');
      if (data?.success) {
        setSelected(prev => ({ ...prev, status: 'IN_PROGRESS' }));
        setTickets(prev => prev.map(t => t.id === selected.id ? { ...t, status: 'IN_PROGRESS' } : t));
        setNotification({ type: 'success', text: t.reopened });
        const detail = await complaintsService.getComplaintById(selected.id);
        if (detail?.success) {
          setSelected(detail.complaint);
          setTimeline(detail.timeline || []);
        }
      }
    } catch (error) {
      console.error('❌ Error reopening ticket:', error);
      setNotification({ type: 'error', text: t.reopenFailed });
    } finally {
      setReopening(false);
    }
  };

  // ============================================================
  // CONFIRMATION
  // ============================================================
  const handleConfirm = () => {
    if (confirmDialog?.onConfirm) confirmDialog.onConfirm();
    setConfirmDialog(null);
  };

  // ============================================================
  // STATS
  // ============================================================
  const stats = {
    total: tickets.length,
    open: tickets.filter(t => ['NEW', 'OPEN', 'WAITING_FOR_USER'].includes(t.status)).length,
    inProgress: tickets.filter(t => t.status === 'IN_PROGRESS').length,
    resolved: tickets.filter(t => t.status === 'RESOLVED').length
  };

  // ============================================================
  // RENDER: CONVERSATION THREAD
  // Builds the threaded conversation from the original complaint
  // description + all replies, ordered by createdAt ASC.
  // ============================================================
  const renderThread = () => {
    // Build messages: original complaint first, then replies
    const messages = [
      {
        id: 'original',
        authorName: selected?.User?.fullName || t.you,
        authorRole: userRole,
        message: selected?.description || '',
        attachments: selected?.attachments || [],
        createdAt: selected?.createdAt,
        isOriginal: true,
      },
      ...(selected?.replies || []).map((reply) => ({
        id: reply.id,
        authorName: reply.authorName,
        authorRole: reply.authorRole,
        message: reply.message,
        attachments: reply.attachments || [],
        createdAt: reply.createdAt,
        isOriginal: false,
      })),
    ];

    return (
      <div className="space-y-3">
        {messages.map((msg, index) => {
          const isMine = msg.isOriginal || ['WORKER', 'EMPLOYER'].includes(msg.authorRole);
          const authorLabel = msg.authorName || (isMine ? t.you : t.support);
          const bubbleClass = isMine
            ? `ml-auto ${th.bubble} border`
            : 'mr-auto bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600';

          return (
            <div key={msg.id || index} className={`flex flex-col max-w-[85%] ${isMine ? 'items-end ml-auto' : 'items-start mr-auto'}`}>
              <div className={`px-4 py-2.5 rounded-2xl ${bubbleClass}`}>
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <UserDisplayName
                    name={authorLabel}
                    role={msg.authorRole}
                    size="sm"
                    className={isMine ? th.textDark : 'text-gray-700 dark:text-gray-200'}
                  />
                  <span className="text-[10px] text-gray-400 dark:text-gray-500">
                    {formatDate(msg.createdAt)}
                  </span>
                </div>
                <p className="text-sm text-gray-700 dark:text-gray-200 whitespace-pre-wrap">
                  {msg.message}
                </p>
                {msg.attachments && msg.attachments.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-2">
                    {msg.attachments.map((url, i) => (
                      <a
                        key={i}
                        href={url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="w-16 h-16 rounded-lg overflow-hidden border border-gray-200 dark:border-gray-600 hover:opacity-80 transition"
                      >
                        <img src={url} alt={`Attachment ${i + 1}`} className="w-full h-full object-cover" />
                      </a>
                    ))}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    );
  };

  // ============================================================
  // RENDER: TIMELINE (separate section)
  // ============================================================
  const renderTimeline = () => {
    if (!timeline.length) {
      return (
        <div className="text-center py-4">
          <p className="text-sm text-gray-500 dark:text-gray-400">No timeline events</p>
        </div>
      );
    }

    return (
      <div className="space-y-2">
        {timeline.map((event, index) => (
          <div key={event.id || index} className="flex gap-3">
            <div className="flex flex-col items-center">
              <div className="w-2 h-2 rounded-full bg-gray-400 dark:bg-gray-500 mt-1.5"></div>
              {index < timeline.length - 1 && <div className="w-px flex-1 bg-gray-200 dark:bg-gray-600"></div>}
            </div>
            <div className="flex-1 pb-2">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {t.eventLabels[event.action] || event.action}
                </p>
                <span className="text-xs text-gray-500 dark:text-gray-400">
                  {formatShortDate(event.createdAt)}
                </span>
              </div>
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-0.5">
                {event.description}
                {event.authorName && ` — ${event.authorName}`}
              </p>
            </div>
          </div>
        ))}
      </div>
    );
  };

  // ============================================================
  // RENDER
  // ============================================================
  return (
    <div className="p-4 md:p-6">
      {/* Notification */}
      {notification && (
        <div className={`mb-4 px-4 py-3 rounded-lg flex items-center gap-2 ${
          notification.type === 'error'
            ? 'bg-red-500/10 border border-red-500/30 text-red-400'
            : 'bg-green-500/10 border border-green-500/30 text-green-400'
        }`}>
          <AlertTriangle size={18} />
          {notification.text}
        </div>
      )}

      {/* Header */}
      <div className={`bg-gradient-to-r ${th.gradient} rounded-2xl p-6 mb-6 text-white`}>
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-full bg-white/20 flex items-center justify-center">
              <LifeBuoy size={24} className="text-white" />
            </div>
            <div>
              <h1 className="text-2xl font-bold">{t.title}</h1>
              <p className="text-white/80 mt-1">{t.subtitle}</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => { loadTickets(); }}
              className="bg-white/20 hover:bg-white/30 px-4 py-2 rounded-lg text-sm font-medium transition flex items-center gap-2"
            >
              <RefreshCw size={16} />
            </button>
            <button
              onClick={() => setShowCreate(!showCreate)}
              className={`${th.headerBtn} px-4 py-2 rounded-lg text-sm font-medium transition-colors flex items-center gap-2 backdrop-blur-sm`}
            >
              {showCreate ? <X size={16} /> : <AlertTriangle size={16} />}
              {showCreate ? t.cancel : t.newTicket}
            </button>
          </div>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {[
          { label: t.stats.total, value: stats.total, icon: Inbox, color: th.text, bg: th.bg },
          { label: t.stats.open, value: stats.open, icon: Clock, color: 'text-yellow-600', bg: 'bg-yellow-50 dark:bg-yellow-900/30' },
          { label: t.stats.inProgress, value: stats.inProgress, icon: AlertCircle, color: 'text-blue-600', bg: 'bg-blue-50 dark:bg-blue-900/30' },
          { label: t.stats.resolved, value: stats.resolved, icon: CheckCircle, color: 'text-green-600', bg: 'bg-green-50 dark:bg-green-900/30' }
        ].map((s, i) => (
          <div key={i} className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-4 border border-gray-100 dark:border-gray-700 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-500 dark:text-gray-400">{s.label}</p>
              <div className={`w-10 h-10 ${s.bg} rounded-lg flex items-center justify-center`}>
                <s.icon size={20} className={s.color} />
              </div>
            </div>
            <p className="text-2xl font-bold text-gray-800 dark:text-white mt-1">{s.value}</p>
          </div>
        ))}
      </div>

      {/* Create Ticket Form */}
      {showCreate && (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-6 border border-gray-100 dark:border-gray-700 mb-6">
          <h3 className="text-lg font-semibold text-gray-800 dark:text-white mb-4 flex items-center gap-2">
            <FileText size={18} className={th.text} />
            {t.newTicket}
          </h3>
          <form onSubmit={handleCreate}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{t.titleLabel} *</label>
                <input
                  type="text"
                  name="subject"
                  value={newTicket.subject}
                  onChange={handleInputChange}
                  required
                  className={`w-full px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg focus:ring-2 ${th.ring} focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white`}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{t.categoryLabel} *</label>
                <select
                  name="category"
                  value={newTicket.category}
                  onChange={handleInputChange}
                  required
                  className={`w-full px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg focus:ring-2 ${th.ring} focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white`}
                >
                  {complaintsService.COMPLAINT_CATEGORIES.map(cat => (
                    <option key={cat} value={cat}>{cat}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{t.priorityLabel} *</label>
                <select
                  name="priority"
                  value={newTicket.priority}
                  onChange={handleInputChange}
                  required
                  className={`w-full px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg focus:ring-2 ${th.ring} focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white`}
                >
                  {complaintsService.COMPLAINT_PRIORITIES.map(pri => (
                    <option key={pri} value={pri}>{pri}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{t.attachmentsLabel}</label>
                <input
                  type="file"
                  multiple
                  onChange={handleAttachmentChange}
                  className={`w-full px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg focus:ring-2 ${th.ring} focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white`}
                />
                {newTicket.attachments.length > 0 && (
                  <div className="flex flex-wrap gap-2 mt-2">
                    {newTicket.attachments.map((url, index) => (
                      <div key={index} className="relative">
                        <img src={url} alt={`Attachment ${index + 1}`} className="w-16 h-16 object-cover rounded-lg border border-gray-200 dark:border-gray-600" />
                        <button
                          type="button"
                          onClick={() => removeAttachment(index)}
                          className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full p-1"
                        >
                          <X size={14} />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
            <div className="mt-4">
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">{t.descriptionLabel} *</label>
              <textarea
                name="description"
                value={newTicket.description}
                onChange={handleInputChange}
                rows="4"
                required
                className={`w-full px-4 py-2.5 border border-gray-200 dark:border-gray-700 rounded-lg focus:ring-2 ${th.ring} focus:border-transparent bg-white dark:bg-gray-700 text-gray-900 dark:text-white`}
              />
            </div>
            <div className="mt-4 flex gap-3">
              <button
                type="submit"
                disabled={submitting}
                className={`px-6 py-2 ${th.button} text-white rounded-lg ${th.buttonHover} transition flex items-center gap-2 disabled:opacity-50`}
              >
                {submitting ? <Loader2 size={18} className="animate-spin" /> : <Send size={18} />}
                {submitting ? t.submitting : t.submit}
              </button>
              <button
                type="button"
                onClick={() => setShowCreate(false)}
                className="px-6 py-2 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:bg-gray-900 transition"
              >
                {t.cancel}
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Filters */}
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-4 border border-gray-100 dark:border-gray-700 mb-6">
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1 relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 dark:text-gray-500" />
            <input
              type="text"
              placeholder={t.searchPlaceholder}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className={`w-full pl-10 pr-4 py-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-white placeholder-gray-400 dark:placeholder-gray-500 rounded-lg focus:outline-none focus:ring-2 ${th.ring} focus:border-transparent`}
            />
          </div>
          <div className="flex flex-wrap gap-2">
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="px-4 py-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-400"
            >
              <option value="all">{t.filters.all}</option>
              <option value="NEW">{t.filters.new}</option>
              <option value="OPEN">{t.filters.open}</option>
              <option value="IN_PROGRESS">{t.filters.inProgress}</option>
              <option value="WAITING_FOR_USER">{t.filters.waiting}</option>
              <option value="ESCALATED">{t.filters.escalated}</option>
              <option value="RESOLVED">{t.filters.resolved}</option>
              <option value="CLOSED">{t.filters.closed}</option>
            </select>
            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value)}
              className="px-4 py-2.5 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 text-gray-700 dark:text-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-400"
            >
              <option value="all">{t.filters.allPriorities}</option>
              {complaintsService.COMPLAINT_PRIORITIES.map(p => (
                <option key={p} value={p}>{p}</option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Results Count */}
      <div className="flex justify-between items-center mb-4">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          {t.showing} <span className="font-semibold text-gray-700 dark:text-gray-300">{filtered.length}</span> {t.tickets}
        </p>
      </div>

      {/* Ticket List */}
      {loading ? (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-12 text-center border border-gray-100 dark:border-gray-700">
          <Loader2 size={32} className={`animate-spin mx-auto ${th.text}`} />
          <p className="mt-4 text-gray-500 dark:text-gray-400">{t.loading}</p>
        </div>
      ) : filtered.length === 0 ? (
        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm p-12 text-center border border-gray-100 dark:border-gray-700">
          <div className="text-6xl mb-4">🎫</div>
          <h3 className="text-xl font-semibold text-gray-800 dark:text-white mb-2">{t.noTickets}</h3>
          <p className="text-gray-500 dark:text-gray-400">{t.noTicketsDesc}</p>
          <button
            onClick={() => setShowCreate(true)}
            className={`mt-4 px-6 py-2 ${th.button} text-white rounded-lg ${th.buttonHover} transition-colors`}
          >
            {t.newTicket}
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {filtered.map((ticket) => {
            const assignedName = ticket.assignedSupport?.fullName || t.unassigned;
            return (
              <div
                key={ticket.id}
                className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden hover:shadow-md transition cursor-pointer"
                onClick={() => handleViewDetails(ticket)}
              >
                <div className="p-4">
                  {/* Top row: ticket id + badges */}
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-gray-100 dark:bg-gray-700 text-xs font-mono font-semibold text-gray-700 dark:text-gray-200">
                      <Tag size={12} />
                      {getTicketNumber(ticket)}
                    </span>
                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${complaintsService.getStatusBadgeClass(ticket.status)}`}>
                      {complaintsService.getStatusLabel(ticket.status)}
                    </span>
                    <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${complaintsService.getPriorityBadgeClass(ticket.priority)}`}>
                      <Flag size={12} />
                      {complaintsService.getPriorityLabel(ticket.priority)}
                    </span>
                    <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300">
                      <FileText size={12} />
                      {ticket.category}
                    </span>
                  </div>

                  {/* Subject + description */}
                  <h3 className="font-semibold text-gray-800 dark:text-white">{ticket.subject}</h3>
                  <p className="text-sm text-gray-600 dark:text-gray-300 mt-1 line-clamp-2">{ticket.description}</p>

                  {/* Meta row */}
                  <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-gray-500 dark:text-gray-400">
                    <span className="inline-flex items-center gap-1">
                      <LifeBuoy size={12} />
                      {t.assigned}: <span className="font-medium text-gray-700 dark:text-gray-200">{assignedName}</span>
                    </span>
                    <span className="text-gray-300 dark:text-gray-600">|</span>
                    <span className="inline-flex items-center gap-1">
                      <Calendar size={12} />
                      {t.created}: {formatShortDate(ticket.createdAt)}
                    </span>
                    <span className="text-gray-300 dark:text-gray-600">|</span>
                    <span className="inline-flex items-center gap-1">
                      <Clock size={12} />
                      {t.lastUpdate}: {formatShortDate(ticket.updatedAt)}
                    </span>
                    <span className="ml-auto inline-flex items-center gap-1 text-gray-400 dark:text-gray-500">
                      {t.viewDetails}
                      <ChevronDown size={14} />
                    </span>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ============================================================
          TICKET DETAILS MODAL
          ============================================================ */}
      {showDetails && selected && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl max-w-4xl w-full max-h-[92dvh] overflow-y-auto border border-gray-200 dark:border-gray-700">
            {/* Header */}
            <div className="sticky top-0 bg-white dark:bg-gray-800 z-10 flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg bg-gray-100 dark:bg-gray-700 text-xs font-mono font-semibold text-gray-700 dark:text-gray-200">
                    <Tag size={12} />
                    {getTicketNumber(selected)}
                  </span>
                  <span className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium ${complaintsService.getStatusBadgeClass(selected.status)}`}>
                    {complaintsService.getStatusLabel(selected.status)}
                  </span>
                </div>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white">{selected.subject}</h2>
              </div>
              <button
                onClick={() => setShowDetails(false)}
                className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors text-gray-400"
              >
                <X size={20} />
              </button>
            </div>

            <div className="p-6 space-y-6">
              {/* Info grid */}
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <Flag size={12} />
                    {t.priority}
                  </p>
                  <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium mt-1 ${complaintsService.getPriorityBadgeClass(selected.priority)}`}>
                    {complaintsService.getPriorityLabel(selected.priority)}
                  </span>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <FileText size={12} />
                    {t.category}
                  </p>
                  <p className="text-sm font-medium text-gray-900 dark:text-white mt-1">{selected.category}</p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <LifeBuoy size={12} />
                    {t.assigned}
                  </p>
                  <p className="text-sm font-medium text-gray-900 dark:text-white mt-1">
                    {selected.assignedSupport?.fullName || t.unassigned}
                  </p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <Calendar size={12} />
                    {t.created}
                  </p>
                  <p className="text-sm font-medium text-gray-900 dark:text-white mt-1">{formatDate(selected.createdAt)}</p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <Clock size={12} />
                    {t.lastUpdate}
                  </p>
                  <p className="text-sm font-medium text-gray-900 dark:text-white mt-1">{formatDate(selected.updatedAt)}</p>
                </div>
                <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-3">
                  <p className="text-xs text-gray-500 dark:text-gray-400 flex items-center gap-1">
                    <Shield size={12} />
                    {t.status}
                  </p>
                  <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium mt-1 ${complaintsService.getStatusBadgeClass(selected.status)}`}>
                    {complaintsService.getStatusLabel(selected.status)}
                  </span>
                </div>
              </div>

              {/* Description */}
              <div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">{t.description}</h4>
                <p className="text-sm text-gray-600 dark:text-gray-400 bg-gray-50 dark:bg-gray-700 rounded-lg p-4 whitespace-pre-wrap">
                  {selected.description}
                </p>
              </div>

              {/* Attachments preview */}
              <div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2 flex items-center gap-2">
                  <Paperclip size={14} />
                  {t.attachments}
                </h4>
                {selected.attachments && selected.attachments.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {selected.attachments.map((url, index) => (
                      <a
                        key={index}
                        href={url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="w-20 h-20 rounded-lg overflow-hidden border border-gray-200 dark:border-gray-600 hover:opacity-80 transition"
                      >
                        <img src={url} alt={`Attachment ${index + 1}`} className="w-full h-full object-cover" />
                      </a>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-gray-500 dark:text-gray-400">{t.noAttachments}</p>
                )}
              </div>

              {/* Conversation thread */}
              <div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
                  <MessageSquare size={14} />
                  {t.conversation}
                </h4>
                {renderThread()}
              </div>

              {/* Timeline (separate section) */}
              <div>
                <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
                  <History size={14} />
                  {t.timeline}
                </h4>
                {renderTimeline()}
              </div>

              {/* Reply box */}
              {!['RESOLVED', 'CLOSED'].includes(selected.status) && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <h4 className="text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">{t.reply}</h4>
                  <div className="flex flex-col sm:flex-row gap-2">
                    <input
                      type="text"
                      value={replyText}
                      onChange={(e) => setReplyText(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault();
                          handleSendReply();
                        }
                      }}
                      placeholder={t.replyPlaceholder}
                      className={`flex-1 min-w-0 px-4 py-2.5 bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg focus:outline-none focus:ring-2 ${th.ring} text-gray-900 dark:text-white`}
                    />
                    <button
                      onClick={handleSendReply}
                      disabled={sendingReply || !replyText.trim()}
                      className={`px-4 py-2.5 ${th.button} text-white rounded-lg ${th.buttonHover} transition disabled:opacity-50 flex items-center gap-2`}
                    >
                      {sendingReply ? <Loader2 size={16} className="animate-spin" /> : <Send size={16} />}
                      {sendingReply ? t.sending : t.sendReply}
                    </button>
                  </div>
                </div>
              )}

              {/* Resolved / Closed notice + Reopen */}
              {(selected.status === 'RESOLVED' || selected.status === 'CLOSED') && (
                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <div className={`rounded-lg p-4 flex items-center gap-2 mb-3 ${
                    selected.status === 'RESOLVED'
                      ? 'bg-green-50 dark:bg-green-900/20'
                      : 'bg-gray-50 dark:bg-gray-700'
                  }`}>
                    {selected.status === 'RESOLVED' ? (
                      <CheckCircle size={18} className="text-green-600" />
                    ) : (
                      <Lock size={18} className="text-gray-500" />
                    )}
                    <p className={`text-sm ${
                      selected.status === 'RESOLVED'
                        ? 'text-green-700 dark:text-green-300'
                        : 'text-gray-600 dark:text-gray-300'
                    }`}>
                      {complaintsService.getStatusLabel(selected.status)} — {formatDate(selected.resolvedAt || selected.closedAt)}
                    </p>
                  </div>
                  <button
                    onClick={() => setConfirmDialog({
                      title: t.reopen,
                      message: t.confirmReopen,
                      onConfirm: handleReopen
                    })}
                    disabled={reopening}
                    className="px-4 py-2.5 bg-blue-500/10 text-blue-600 dark:text-blue-400 rounded-lg hover:bg-blue-500/20 transition flex items-center gap-2 disabled:opacity-50"
                  >
                    {reopening ? <Loader2 size={16} className="animate-spin" /> : <RotateCcw size={16} />}
                    {reopening ? t.reopening : t.reopen}
                  </button>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-end gap-3 p-6 border-t border-gray-200 dark:border-gray-700">
              <button
                onClick={() => setShowDetails(false)}
                className="px-4 py-2.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition-colors text-sm"
              >
                {t.close}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Dialog */}
      {confirmDialog && (
        <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4">
          <div className="bg-white dark:bg-gray-800 rounded-2xl max-w-md w-full border border-gray-200 dark:border-gray-700 p-6">
            <div className="flex items-center gap-3 mb-4">
              <div className={`w-10 h-10 ${th.bg} rounded-lg flex items-center justify-center`}>
                <AlertTriangle size={20} className={th.text} />
              </div>
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white">{confirmDialog.title}</h3>
            </div>
            <p className="text-sm text-gray-600 dark:text-gray-400 mb-6">{confirmDialog.message}</p>
            <div className="flex gap-3">
              <button
                onClick={() => setConfirmDialog(null)}
                className="flex-1 px-4 py-2.5 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 transition"
              >
                {t.cancel}
              </button>
              <button
                onClick={handleConfirm}
                className={`flex-1 px-4 py-2.5 ${th.button} text-white rounded-lg ${th.buttonHover} transition`}
              >
                {t.confirm}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TicketSystem;