import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, BookOpen, ChevronDown, Filter, RefreshCw, Scale, Wallet } from 'lucide-react';
import api from '../utils/api';
import DashboardLayout from '../components/layout/DashboardLayout';
import DashboardHeader from '../components/layout/DashboardHeader';

const money = (amount, currency) => `${Number(amount || 0).toLocaleString(undefined, { maximumFractionDigits: 3 })} ${currency}`;
const enumLabel = (t, value) => t(`financialCenter.enum_${value}`, { defaultValue: t('financialCenter.enum_unknown') });
const reasonLabel = (t, code) => t(`financialCenter.reason_${code}`, { defaultValue: t('financialCenter.reason_unknown') });
const MoneyList = ({ rows = [], empty, large = false }) => {
  const { t } = useTranslation();
  return rows.length ? (
  <div className={large ? 'space-y-2' : 'space-y-1.5'}>{rows.map((row) => (
    <div key={`${row.provider || ''}-${row.purpose || ''}-${row.paymentStatus || ''}-${row.currency}`} className={large ? 'text-2xl md:text-3xl font-bold tracking-tight' : 'text-base font-semibold'}>
      {money(row.amount, row.currency)}
      {(row.provider || row.purpose || row.paymentStatus) && <span className="ml-2 text-xs font-medium uppercase text-gray-400">{enumLabel(t, row.provider || row.purpose || row.paymentStatus)}</span>}
    </div>
  ))}</div>
) : <span className="text-sm text-gray-400">{empty}</span>;
};

const ACCENTS = { yellow: ['bg-yellow-500/10','text-yellow-500'], green: ['bg-green-500/10','text-green-500'], blue: ['bg-blue-500/10','text-blue-500'] };
const TONES = { yellow: 'border-yellow-500/25 bg-yellow-500/10', green: 'border-green-500/25 bg-green-500/10', red: 'border-red-500/25 bg-red-500/10', amber: 'border-amber-500/25 bg-amber-500/10' };
const METRIC_TONES = { gray:'bg-gray-500/10', green:'bg-green-500/10', red:'bg-red-500/10', amber:'bg-amber-500/10' };
const Panel = ({ title, subtitle, icon: Icon, children, accent = 'yellow' }) => (
  <section className="min-w-0 rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-5 md:p-6 shadow-sm">
    <div className="mb-5 flex items-start gap-3"><div className={`rounded-xl p-2.5 ${ACCENTS[accent]?.[0] || ACCENTS.yellow[0]}`}><Icon size={20} className={ACCENTS[accent]?.[1] || ACCENTS.yellow[1]} /></div><div><h2 className="text-lg font-bold text-gray-900 dark:text-white">{title}</h2>{subtitle && <p className="mt-0.5 text-sm text-gray-500">{subtitle}</p>}</div></div>
    {children}
  </section>
);

const HeroCard = ({ title, icon: Icon, rows, children, tone = 'yellow', empty }) => (
  <div className={`relative overflow-hidden rounded-2xl border bg-gradient-to-br via-white to-white dark:via-gray-800 dark:to-gray-800 p-6 min-h-44 shadow-sm ${TONES[tone] || TONES.yellow}`}>
    <div className="flex items-center justify-between gap-3"><p className="font-semibold text-gray-600 dark:text-gray-300">{title}</p><div className="rounded-xl bg-white/60 dark:bg-black/20 p-2"><Icon size={22} className="text-gray-700 dark:text-gray-200" /></div></div>
    <div className="mt-6">{rows !== undefined && <MoneyList rows={rows} empty={empty} large />}{children}</div>
  </div>
);

const Metric = ({ label, value, tone = 'gray' }) => { const { t } = useTranslation(); return <div className={`rounded-xl p-4 ${METRIC_TONES[tone] || METRIC_TONES.gray}`}><p className="text-xs font-semibold uppercase tracking-wide text-gray-500">{enumLabel(t, label)}</p><p className="mt-1 text-2xl font-bold text-gray-900 dark:text-white">{value || 0}</p></div>; };
const StatusBadge = ({ state }) => { const { t } = useTranslation(); const cls = state === 'MISMATCH' ? 'bg-red-100 text-red-700' : state === 'MATCHED' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-800'; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${cls}`}>{enumLabel(t, state)}</span>; };

const AdminFinancialCenter = () => {
  const { t } = useTranslation();
  const f = (key) => t(`financialCenter.${key}`);
  const [activeTab, setActiveTab] = useState('overview');
  const [showAllReview, setShowAllReview] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [filters, setFilters] = useState({ range: '30d', currency: 'ALL', provider: 'all', purpose: 'ALL', paymentStatus: 'all', refundStatus: 'all', reconciliationState: 'ALL', from: '', to: '' });

  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = Object.fromEntries(Object.entries(filters).filter(([, value]) => value !== '')); const response = await api.get('/api/admin/financial-center', { params }); setData(response.data?.financialCenter || null); } catch (err) { setError(err.response?.data?.message || f('loadFailed')); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  const update = (key) => (event) => setFilters((current) => ({ ...current, [key]: event.target.value }));
  const tabs = ['overview', 'revenue', 'refunds', 'providers', 'reconciliation'];
  const summary = data?.summary || {};
  const review = data?.reconciliation?.reviewSummary || {};
  const reviewRows = useMemo(() => (data?.reconciliation?.needsReview || []).slice(0, showAllReview ? 50 : 5), [data, showAllReview]);
  const FilterSelect = ({ label, name, children }) => {
    return <label className="min-w-0 text-xs font-semibold text-gray-500">{label}<select value={filters[name]} onChange={update(name)} className="mt-1.5 w-full rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 px-3 py-2.5 text-sm text-gray-800 dark:text-gray-100">{children}</select></label>;
  };

  return <DashboardLayout requiredRole="ADMIN"><DashboardHeader title={f('title')} /><div className="p-4 md:p-6 lg:p-8 space-y-7" dir="ltr">
    <header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-yellow-600">{f('nav')}</p><h1 className="mt-1 text-3xl md:text-4xl font-bold text-gray-900 dark:text-white">{f('title')}</h1><p className="mt-2 max-w-2xl text-gray-500">{f('subtitle')}</p></div><button onClick={load} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-yellow-500 px-4 py-2.5 font-semibold text-black disabled:opacity-50"><RefreshCw size={17} className={loading ? 'animate-spin' : ''} />{f('refresh')}</button></header>

    <section className="rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-sm"><button onClick={() => setFiltersOpen((v) => !v)} className="flex w-full items-center justify-between p-4 md:p-5"><span className="flex items-center gap-2 font-semibold"><Filter size={18} className="text-yellow-500" />{f('filters')}</span><ChevronDown size={18} className={`transition ${filtersOpen ? 'rotate-180' : ''}`} /></button>{filtersOpen && <div className="border-t dark:border-gray-700 p-4 md:p-5"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><FilterSelect label={f('dateRange')} name="range"><option value="7d">{f('last7')}</option><option value="30d">{f('last30')}</option><option value="90d">{f('last90')}</option><option value="all">{f('allTime')}</option><option value="custom">{f('custom')}</option></FilterSelect><FilterSelect label={f('currency')} name="currency"><option value="ALL">{f('all')}</option>{['EGP','USD','EUR','GBP','SAR','AED'].map((x)=><option key={x}>{x}</option>)}</FilterSelect><FilterSelect label={f('provider')} name="provider"><option value="all">{f('all')}</option><option value="paypal">PayPal</option><option value="paymob">Paymob</option><option value="legacy">{f('legacy')}</option></FilterSelect><FilterSelect label={f('purpose')} name="purpose"><option value="ALL">{f('all')}</option><option value="COMMISSION">{f('commission')}</option><option value="SUBSCRIPTION">{f('subscription')}</option><option value="LEGACY_OTHER">{f('legacyOther')}</option></FilterSelect><FilterSelect label={f('paymentStatus')} name="paymentStatus"><option value="all">{f('all')}</option>{['pending','processing','completed','failed'].map((x)=><option key={x}>{enumLabel(t,x)}</option>)}</FilterSelect><FilterSelect label={f('refundStatus')} name="refundStatus"><option value="all">{f('all')}</option>{['pending','processing','completed','failed','review_required'].map((x)=><option key={x}>{enumLabel(t,x)}</option>)}</FilterSelect><FilterSelect label={f('reconciliation')} name="reconciliationState"><option value="ALL">{f('all')}</option>{['MATCHED','MISMATCH','REVIEW_REQUIRED'].map((x)=><option key={x}>{enumLabel(t,x)}</option>)}</FilterSelect>{filters.range === 'custom' && <><label className="text-xs font-semibold text-gray-500">{f('from')}<input type="date" value={filters.from} onChange={update('from')} className="mt-1.5 w-full rounded-xl border p-2.5 bg-transparent" /></label><label className="text-xs font-semibold text-gray-500">{f('to')}<input type="date" value={filters.to} onChange={update('to')} className="mt-1.5 w-full rounded-xl border p-2.5 bg-transparent" /></label></>}</div></div>}</section>

    <nav className="flex gap-2 overflow-x-auto pb-1">{tabs.map((tab)=><button key={tab} onClick={()=>setActiveTab(tab)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-500 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-gray-900 ${activeTab===tab?'border-yellow-500 bg-yellow-500 text-black shadow-sm hover:bg-yellow-400':'border-gray-200 bg-white text-gray-600 hover:border-yellow-400 hover:bg-yellow-50 hover:text-gray-900 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-300 dark:hover:border-yellow-500 dark:hover:bg-yellow-500/10 dark:hover:text-white'}`}>{f(tab)}</button>)}</nav>
    {error && <div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{loading && !data ? <div className="py-24 text-center text-gray-500">{f('loading')}</div> : data && <>
      {activeTab === 'overview' && <div className="space-y-7"><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-5"><HeroCard title={f('grossMoneyIn')} icon={ArrowDownLeft} rows={summary.grossMoneyIn} empty={f('noData')} tone="green"/><HeroCard title={f('completedRefunds')} icon={ArrowUpRight} rows={summary.completedBookRefunds} empty={f('noData')} tone="red"/><HeroCard title={f('netBookRevenue')} icon={Wallet} rows={summary.netBookRevenue} empty={f('noData')} tone="yellow"/><HeroCard title={f('needsReview')} icon={AlertTriangle} empty={f('noData')} tone="amber"><div className="text-4xl font-bold">{summary.paymentsNeedingReview || 0}</div><div className="mt-4 grid grid-cols-3 gap-2"><div className="text-xs"><b className="block text-lg text-red-600">{review.criticalMismatchCount || 0}</b>{f('criticalMismatch')}</div><div className="text-xs"><b className="block text-lg text-amber-600">{review.generalReviewRequiredCount || 0}</b>{f('generalReview')}</div><div className="text-xs"><b className="block text-lg text-gray-500">{review.legacyEvidenceGapCount || 0}</b>{f('legacyEvidence')}</div></div></HeroCard></div><div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><Panel title={f('bookFinancials')} subtitle={f('bookAuthorityNote')} icon={BookOpen} accent="green"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div><p className="text-xs uppercase text-gray-500">{f('grossMoneyIn')}</p><MoneyList rows={summary.grossMoneyIn} empty={f('noData')}/></div><div><p className="text-xs uppercase text-gray-500">{f('bookRefundImpact')}</p><MoneyList rows={summary.completedBookRefunds} empty={f('noData')}/></div><div><p className="text-xs uppercase text-gray-500">{f('netBookRevenue')}</p><MoneyList rows={summary.netBookRevenue} empty={f('noData')}/></div></div></Panel><Panel title={f('providerMovement')} subtitle={f('providerEvidenceNote')} icon={Scale} accent="blue"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div><p className="text-xs uppercase text-gray-500">{f('providerCharges')}</p><MoneyList rows={data.providerMovement.charges} empty={f('noData')}/></div><div><p className="text-xs uppercase text-gray-500">{f('providerRefunds')}</p><MoneyList rows={data.providerMovement.refunds} empty={f('noData')}/></div><div><p className="text-xs uppercase text-gray-500">{f('providerNet')}</p><MoneyList rows={data.providerMovement.net} empty={f('noData')}/></div></div></Panel></div></div>}
      {activeTab === 'revenue' && <div className="grid grid-cols-1 xl:grid-cols-2 gap-6"><Panel title={f('commissionFinancials')} subtitle={f('obligationNote')} icon={Wallet}><p className="text-xs uppercase text-gray-500">{f('completedRevenue')}</p><MoneyList rows={data.commission.completedRevenue} empty={f('noData')} large/><div className="mt-5 grid grid-cols-1 sm:grid-cols-3 gap-3"><div><p className="text-xs text-gray-500">{enumLabel(t,'completed')}</p><MoneyList rows={data.commission.amountsByStatus.filter(x=>x.paymentStatus==='completed')} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{enumLabel(t,'pending')}</p><MoneyList rows={data.commission.amountsByStatus.filter(x=>['pending','processing'].includes(x.paymentStatus))} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{enumLabel(t,'failed')}</p><MoneyList rows={data.commission.amountsByStatus.filter(x=>x.paymentStatus==='failed')} empty={f('noData')}/></div></div><div className="my-6 border-t dark:border-gray-700"/><h3 className="font-semibold">{f('totalObligation')}</h3><div className="mt-3 grid grid-cols-1 sm:grid-cols-3 gap-3"><div><p className="text-xs text-gray-500">{f('totalObligation')}</p><MoneyList rows={data.commission.obligations} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{f('paidObligation')}</p><MoneyList rows={data.commission.paidObligations} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{f('outstandingObligation')}</p><MoneyList rows={data.commission.outstandingObligations} empty={f('noData')}/></div></div></Panel><Panel title={f('subscriptionFinancials')} icon={BookOpen}><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div><p className="text-xs text-gray-500">{f('completedRevenue')}</p><MoneyList rows={data.subscription.completedRevenue} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{f('completedRefunds')}</p><MoneyList rows={data.subscription.completedRefunds} empty={f('noData')}/></div><div><p className="text-xs text-gray-500">{f('netBookRevenue')}</p><MoneyList rows={data.subscription.netRevenue} empty={f('noData')}/></div></div><div className="my-6 border-t dark:border-gray-700"/><h3 className="font-semibold mb-3">{f('grantCounts')}</h3><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{Object.entries(data.subscription.grantCounts).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</div></Panel><Panel title={f('bookRevenueByPurpose')} subtitle={f('bookAuthorityNote')} icon={BookOpen}><MoneyList rows={data.bookRevenue.byPurpose} empty={f('noData')} large/></Panel></div>}
      {activeTab === 'refunds' && <div className="grid grid-cols-1 xl:grid-cols-2 gap-6"><Panel title={f('refundSummary')} icon={ArrowUpRight}><div className="grid grid-cols-2 sm:grid-cols-5 gap-3">{['pending','processing','completed','failed','review_required'].map(k=><Metric key={k} label={k} value={data.refunds.statusCounts[k]}/>)}</div><h3 className="mt-6 mb-3 font-semibold">{f('types')}</h3><div className="grid grid-cols-2 gap-3">{Object.entries(data.refunds.typeCounts).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</div></Panel><Panel title={f('completedRefunds')} subtitle={f('providerEvidenceNote')} icon={Scale}><div className="grid grid-cols-1 sm:grid-cols-2 gap-6"><div><p className="text-xs uppercase text-gray-500">{f('bookRefundImpact')}</p><MoneyList rows={data.refunds.completedBookImpact} empty={f('noData')} large/></div><div className="border-t sm:border-t-0 sm:border-l pt-4 sm:pt-0 sm:pl-6 dark:border-gray-700"><p className="text-xs uppercase text-gray-500">{f('providerRefundOutflow')}</p><MoneyList rows={data.refunds.completedProviderOutflow} empty={f('noData')} large/></div></div></Panel></div>}
      {activeTab === 'providers' && <Panel title={f('providerMovement')} subtitle={f('providerEvidenceNote')} icon={Scale} accent="blue"><div className="grid grid-cols-1 md:grid-cols-3 gap-5"><div className="rounded-xl bg-blue-50 dark:bg-blue-950/20 p-5"><p className="text-sm font-semibold text-blue-700">{f('providerCharges')}</p><div className="mt-3"><MoneyList rows={data.providerMovement.charges} empty={f('noData')} large/></div></div><div className="rounded-xl bg-red-50 dark:bg-red-950/20 p-5"><p className="text-sm font-semibold text-red-700">{f('providerRefunds')}</p><div className="mt-3"><MoneyList rows={data.providerMovement.refunds} empty={f('noData')} large/></div></div><div className="rounded-xl bg-gray-50 dark:bg-gray-900/40 p-5"><p className="text-sm font-semibold">{f('providerNet')}</p><div className="mt-3"><MoneyList rows={data.providerMovement.net} empty={f('noData')} large/></div></div></div></Panel>}
      {activeTab === 'reconciliation' && <div className="space-y-6"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><Metric label="MATCHED" value={data.reconciliation.counts.MATCHED} tone="green"/><Metric label="MISMATCH" value={data.reconciliation.counts.MISMATCH} tone="red"/><Metric label="REVIEW_REQUIRED" value={data.reconciliation.counts.REVIEW_REQUIRED} tone="amber"/></div><div className="grid grid-cols-1 xl:grid-cols-3 gap-6"><Panel title={f('topReasons')} icon={AlertTriangle}><div className="space-y-3">{data.reconciliation.topReasons.map(x=><div key={x.code} className="flex items-center justify-between gap-3"><span className="text-sm text-gray-600 dark:text-gray-300">{reasonLabel(t,x.code)}</span><span className="rounded-full bg-gray-100 dark:bg-gray-700 px-2.5 py-1 text-xs font-bold">{x.count}</span></div>)}</div></Panel><div className="xl:col-span-2"><Panel title={f('needsReview')} icon={AlertTriangle}>{reviewRows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left text-xs uppercase tracking-wide text-gray-500"><th className="pb-3">{f('payment')}</th><th className="pb-3">{f('amount')}</th><th className="pb-3">{f('provider')}</th><th className="pb-3">{f('state')}</th><th className="pb-3">{f('reasons')}</th><th className="pb-3">{f('dateRange')}</th></tr></thead><tbody>{reviewRows.map(row=><tr key={row.paymentId} className="border-t dark:border-gray-700"><td className="py-3 pr-3"><Link to="/admin/payments" className="font-medium text-yellow-600 hover:underline">{row.orderId}</Link></td><td className="py-3 pr-3 whitespace-nowrap">{money(row.amount,row.currency)}</td><td className="py-3 pr-3 capitalize">{enumLabel(t,row.provider)}</td><td className="py-3 pr-3"><StatusBadge state={row.state}/></td><td className="py-3 pr-3 max-w-xs truncate" title={row.reasons.map(x=>reasonLabel(t,x.code)).join(', ')}>{reasonLabel(t,row.reasons[0]?.code)}</td><td className="py-3 whitespace-nowrap">{new Date(row.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>:<p className="text-gray-400">{f('noReview')}</p>}{(data.reconciliation.needsReview||[]).length>5&&<button onClick={()=>setShowAllReview(v=>!v)} className="mt-5 text-sm font-semibold text-yellow-600">{showAllReview?f('showLess'):f('viewAll')}</button>}</Panel></div></div></div>}
    </>}</div></DashboardLayout>;
};
export default AdminFinancialCenter;
